### ISSUE TITLE
`cf-component-label` throws an error

### ISSUE THREAD

**Issue by koddsson** [cloudflare/cf-ui#234] opened 2017-05-31 10:12 UTC
See: https://www.webpackbin.com/bins/-KlSz31gitKKN_SLzWkp for reproduction.

**Comment by koddsson** [comment] 2017-05-31 10:21
This is actually a integration error that's not super apperent. I think it's just missing the `fela` context.

**Comment by wyuenho** [comment] 2017-06-13 15:28
I think this is very surprising to me as well. I think we are moving towards providing both unstyled and styled components. cf-component-label, but in reality, unstyled components are still styled, they are just "unthemed", and should be called as such.

A related issue is, I think we should also provide completely unstyled components. I'll file a ticket for that later to lay out the reason.

**Comment by tajo** [comment] 2017-06-22 19:57
> This is actually a integration error that's not super apperent. I think it's just missing the fela context.

Not a bug. It's missing the base theme. You would have to add `<ThemeProvider>` and pass down `cf-style-const/variables` to make your example working (also you missed required `type` prop for the label). Or just can [just use](https://www.webpackbin.com/bins/-KnGLnwBodTSvrVAJzmo) `cf-style-provider/<StyleProvider>` that does all that.

**Closed by tajo** 2017-06-22 19:57 UTC
Labels: bug
